#!/bin/bash
#
# FILE: downloadEclipseUpdSite
#
# ABSTRACT: Download a eclipse update site into a zip.
#
# AUTHOR: Ralf Schandl <ralf.schandl@de.ibm.com>
#

script_name="$(basename "$0")"

eclipse_home=/opt/eclipse/eclipse-current

if [ $# != 2 ]; then
    echo "Usage: $script_name <UpdSite-URL> <ZipName>"
    exit 1
fi

updateSite=$1
zip=$2

case $zip in
    *.zip) :
        ;;
    *)
        zip=$zip.zip
        ;;
esac

tmpDir=$(mktemp --tmpdir -d upd-site-XXXXX)
# shellcheck disable=SC2064
trap "rm -rf $tmpDir" EXIT

DL_INFO="$tmpDir/download-info.txt"

$eclipse_home/eclipse -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source "$1" -destination "$tmpDir"
$eclipse_home/eclipse -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication -source "$1" -destination "$tmpDir"

echo "URL:  $updateSite" > "$DL_INFO"
echo "Date: $(date "+%Y-%m-%dT%H.%M.%S%z")" >> "$DL_INFO"

(cd "$tmpDir" && zip -r - ./*) > "$zip"

