#!/bin/bash
#
# FILE: escfilter
#
# ABSTRACT: Filters out ANSI escape seequences
#
# AUTHOR: Ralf Schandl
#

while read -r l; do
    # shellcheck disable=SC2001
    echo "$l" | sed "s/\[[^A-Za-z]*[A-Za-z]//"
done

