#!/bin/bash
#
# FILE: nettop
#
# ABSTRACT: Starts iftop for a connected iterface
#
# AUTHOR: Ralf Schandl
#

if [ "$(id -un)" != "root" ]; then
    echo "Need root - sudoing..."
    exec sudo "$0" "$@"
fi

typeset -a if_list
for iface in $(ip -o a | cut '-d ' -f2 | sort -u); do
    case $iface in
        lo) : ;;
        docker*) : ;;
        vir*) : ;;
        *)
            if_list+=( "$iface" )
            ;;
    esac
done

if [ "${#if_list[@]}" -eq 0 ]; then
    echo >&2 "No interface"
    exit 1
fi

if [ "${#if_list[@]}" -gt 1 ]; then
    select i in "${if_list[@]}"; do
        interf=$i
        break
    done
else
    interf="${if_list[0]}"
fi

echo "Starting iftop on interface $interf"
iftop -i "$interf"

